name: Build and Test

# References:
#  - https://github.com/actions/setup-dotnet/blob/main/.github/workflows/test-dotnet.yml
#  - https://github.com/marketplace/actions/setup-net-core-sdk

on:
  pull_request:
    branches:
      - main
      - releases/*
    paths:
      - 'TaskSample/**'
      - '.github/workflows/build-test.yml'
      - '!TaskSample/**/*.md'
  push:
    branches:
      - main
      - releases/*
    paths:
      - 'TaskSample/**'
      - '.github/workflows/build-test.yml'
      - '!TaskSample/**/*.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: ['7.x']
        include:
          - os: ubuntu-latest
            dotnet: '7.x'
            publish: true

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build Task Solutionoo
        run: dotnet build TaskSample.sln --configuration Release

      - name: Run Task Unit Tests
        run: dotnet test TaskSample.sln --configuration Release --no-build --no-restore --verbosity normal

      - name: Deploy Task API to Azure
        if: ${{ matrix.publish == 'true' }}
        run: dotnet publish TaskSample/TaskApi/TaskApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/task-api

