name: Build and Test

# References:
#  - https://github.com/actions/setup-dotnet/blob/main/.github/workflows/test-dotnet.yml
#  - https://github.com/marketplace/actions/setup-net-core-sdk

on:
  pull_request:
    branches:
      - main
      - releases/*
    paths:
      - 'pester-api-testing/**'
      - '.github/workflows/pester-api-testing-build.yml'
      - '!pester-api-testing/**/*.md'
  push:
    branches:
      - '*'
    paths:
      - 'pester-api-testing/**'
      - '.github/workflows/pester-api-testing-build.yml'
      - '!pester-api-testing/**/*.md'

jobs:
  pester-test:
    name: PowerShell Api Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Rest-Api Helper Unit and Integration Tests
        shell: pwsh
        run: |
          ./pester-api-testing/Invoke-RestApi-Tests.ps1 -IntegrationBaseUrl  'https://postman-load-test.azurewebsites.net/' -PassThru 

      - name: Validate Api Tests Against Production 🤨
        shell: pwsh
        run: |
          ./pester-api-testing/Invoke-ApiSmokeTests.ps1 -IntegrationBaseUrl 'https://postman-load-test.azurewebsites.net/' -PassThru