name: Test dotnet

# References:
#  - https://github.com/actions/setup-dotnet/blob/main/.github/workflows/test-dotnet.yml
#  - https://github.com/marketplace/actions/setup-net-core-sdk

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.x']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - run: dotnet build TaskSample/TaskSample.sln 