name: Test dotnet

# References:
#  - https://github.com/actions/setup-dotnet/blob/main/.github/workflows/test-dotnet.yml
#  - https://github.com/marketplace/actions/setup-net-core-sdk

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.x']

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Solution Build
        run: dotnet build TaskSample/TaskSample.sln --configuration Release
      - name: Solution Test
        run: dotnet test TaskSample/TaskSample.sln --no-build --no-restore --verbosity normal --framework ${{ matrix.dotnet-version }}